name: Example workflow
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
          - name: Ahk2Exe
            # You may pin to the exact commit or the version.
            # uses: nekocodeX/GitHub-Action-Ahk2Exe@2556e30cb7e6902c002aa087ee8e43b206371a4d
            uses: nekocodeX/GitHub-Action-Ahk2Exe@v1.1.0
            with:
              # The path or file name of the AutoHotKey script to compile
              in: NetworkSwitch.ahk
              out: NetworkSwitch.exe
              icon: network-switch-icon.ico
              base: Ahk2Exe.exe
                    
